### Linear Algebra with TF
I found some inspiration [here](https://nbviewer.org/github/adhiraiyan/DeepLearningWithTF2.0/blob/master/notebooks/02.00-Linear-Algebra.ipynb)

#### 1. Matrix operations!

In [3]:
import tensorflow as tf
import sys
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
print(tf.__version__)

2.16.1


In [8]:
# let's create a ones 3x3 rank 2 tensor
rank_2_tensor_A = tf.ones([3,3],name="Matrix A")
print("3x3 Rank 2 Tensor A: \n{}\n".format(rank_2_tensor_A)) #format method in Python 3
rank_2_tensor_B = tf.constant([[3,2,1],[3,4,5],[7,6,5]],name='MatrixB',dtype=tf.float32)
print("3x3 Rank Tensor B: \n{}\n".format(rank_2_tensor_B)) #format method in Python
rank_2_tensor_C = tf.add(rank_2_tensor_A, rank_2_tensor_B, name ="MatrixC")
print("Rank 2 Tensor C with shape={} and elements: \n{}".format(rank_2_tensor_C.shape,rank_2_tensor_C))


3x3 Rank 2 Tensor A: 
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

3x3 Rank Tensor B: 
[[3. 2. 1.]
 [3. 4. 5.]
 [7. 6. 5.]]

Rank 2 Tensor C with shape=(3, 3) and elements: 
[[4. 3. 2.]
 [4. 5. 6.]
 [8. 7. 6.]]


In [14]:
#lets see what happens when the shapes are not the same
two_by_three =tf.ones([2,3],name="Matrix D")

try:

    incompatible =tf.add(rank_2_tensor_A,two_by_three)
except:
    print("""incompatable shapes to add with two_by_three of shape {0} and 3x3 Rank 2 Tensor B of shape {1}""".format(two_by_three.shape,rank_2_tensor_A.shape)) #Here I am learning the use of the format and the string with the positional element


incompatable shapes to add with two_by_three of shape (2, 3) and 3x3 Rank 2 Tensor B of shape (3, 3)


2024-06-12 15:05:06.102733: W tensorflow/core/framework/local_rendezvous.cc:404] Local rendezvous is aborting with status: INVALID_ARGUMENT: Incompatible shapes: [3,3] vs. [2,3]


In [27]:
#Creating a scalar a,c, and Matrix B
rank_0_tensor_a = tf.constant(2,name="scalar_A",dtype=tf.float32)
rank_2_tensor_B = tf.constant([[1,2,3],[4,5,6],[7,8,9]],name='MatrixB',dtype=tf.float32)
rank_0_tensor_c = tf.constant(3,name="scalar_c",dtype=tf.float32)
# multiplying aB
multiply_scalar = tf.multiply(rank_0_tensor_a, rank_2_tensor_B)
print(" 3 x 3 Rank 1 Tensor: \n{0}\n".format(multiply_scalar))
#rank_0_tensor_a.name I still do not know how to use the name attribute; quite confusing for me
#adding aB+c
rank_2_tensor_D = tf.add(multiply_scalar,rank_0_tensor_c,name="matrixD")
print("""Original Rank 2 Tensor B: \n{0} \n\nScalar a: {1}
Rank 2 Tensor for aB: \n{2} \n\nScalar c: {3} \nRank 2 Tensor D = aB + c: \n{4}
""".format(rank_2_tensor_B, rank_0_tensor_a, multiply_scalar, rank_0_tensor_c, rank_2_tensor_D))


 3 x 3 Rank 1 Tensor: 
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Original Rank 2 Tensor B: 
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] 

Scalar a: 2.0
Rank 2 Tensor for aB: 
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]] 

Scalar c: 3.0 
Rank 2 Tensor D = aB + c: 
[[ 5.  7.  9.]
 [11. 13. 15.]
 [17. 19. 21.]]



An important operations is the transpose matrix

In [28]:
#Creating a Matrix E
rank_2_tensor_E = tf.constant([[1,2,3],[4,5,6]])
#Transposing the Matrix E
transpose_E = tf.transpose(rank_2_tensor_E, name="Transpose_E")